nelmio_api_doc:
    documentation:
        info:
            title: Star Wars Api
            description: This is an awesome Star Wars Api!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    models:
        use_jms: false
        names:
            - { alias: Starship, type: App\Starships\Domain\Model\StarshipDTO }
            - { alias: Planet, type: App\Planets\Domain\Model\PlanetDTO }
            - { alias: Film, type   : App\Films\Domain\Model\FilmDTO }


